/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3.interfaz;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author salag601
 */
public class PanelConsultas extends javax.swing.JPanel {

    /**
     * Creates new form PanelConsultas
     */
    public PanelConsultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textcalcedad = new javax.swing.JTextField();
        textcalcant = new javax.swing.JTextField();
        textcalcprest = new javax.swing.JTextField();
        butonCalcEdad = new javax.swing.JButton();
        butonCalcAntig = new javax.swing.JButton();
        butonCalcPrest = new javax.swing.JButton();

        textcalcedad.setEditable(false);

        textcalcant.setEditable(false);

        textcalcprest.setEditable(false);

        butonCalcEdad.setText("Calcular Edad");
        butonCalcEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonCalcEdadActionPerformed(evt);
            }
        });

        butonCalcAntig.setText("Calcular Antiguedad");

        butonCalcPrest.setText("Calcular Prestaciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(butonCalcPrest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butonCalcAntig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butonCalcEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textcalcant, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(textcalcedad)
                    .addComponent(textcalcprest))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textcalcedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butonCalcEdad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textcalcant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butonCalcAntig))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textcalcprest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butonCalcPrest))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butonCalcEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonCalcEdadActionPerformed
      
        String idCampo = InterfazEmpleado.textId.getText();

        String request = "SELECT * FROM empleados WHERE DNI = "+ idCampo;        
        
        try {
            Connection conexionsql=DriverManager.getConnection("jdbc:mysql://localhost:3306/empleados", "root", "root");
            
            Statement statement = conexionsql.createStatement();
            
            ResultSet resultset = statement.executeQuery(request);

            while(resultset.next()){
                
                textNombre.setText(resultset.getString("Nombre"));
                textApellido.setText(resultset.getString("Apellido"));
                textSexo.setText(resultset.getString("Sexo"));
                textFNacim.setText(resultset.getString("FechaNacimiento"));
                textFechaIngr.setText(resultset.getString("FechaIngreso"));
                
            }
            
            //textNombre.setText(resultset.getString("Nombre"));
            
        } catch (SQLException ex) {
            Logger.getLogger(InterfazEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        } // TODO add your handling code here:
    }//GEN-LAST:event_butonCalcEdadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonCalcAntig;
    private javax.swing.JButton butonCalcEdad;
    private javax.swing.JButton butonCalcPrest;
    private javax.swing.JTextField textcalcant;
    private javax.swing.JTextField textcalcedad;
    private javax.swing.JTextField textcalcprest;
    // End of variables declaration//GEN-END:variables
}
